Basic http auth snippet
cloudflare/template-registry pull request #19
Opened 2020-04-06 16:14 UTC by maximivanov

Adding an example with Basic HTTP authentication as suggested by @victoriabernard92 

Source PR: https://github.com/south-lane/cf-worker-basic-http-auth/pull/1

2020-04-06 16:18 UTC, maximivanov commented
I may need to reorder things in code to follow the guideline. On it.

2020-04-06 16:22 UTC, exvuma reviewed
Thanks for adding this could you make sure to add an [id.toml](https://github.com/ashleygwilliams/template-registry/blob/master/CONTRIBUTING.md#rust-styleguide) ?

2020-04-06 17:27 UTC, maximivanov commented
@victoriabernard92 toml file added. I was not sure about `share_url` as there's some difference in docs and in other snippets on how to define it. Some do not even have it so I guess it's no longer used.

Also reordered code blocks. Let me know if it works.

2020-04-14 18:36 UTC, maximivanov commented
@victoriabernard92 anything else to fix in this PR?

2020-04-15 21:31 UTC, exvuma requested changes

2020-04-15 21:31 UTC, victoriabernard92 commented on templates/meta_data/auth_basic_http.toml
> +share_url="/templates/pages/auth_basic_http"
```suggestion
```

You're right you don't actually need this

2020-04-15 21:31 UTC, victoriabernard92 commented on templates/meta_data/auth_basic_http.toml
> +description = "Password-protect whole websites or specific areas/pages. E.g. limit access to a staging version of a website you're building."
```suggestion
description = "Password-protect whole websites or specific areas/pages. Browsers will prompt for a password and username - hardcoded as `demouser`/`demopassword` - before serving a protected page. This uses basic authentication through the [`WWW-Authorization` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication).
```

2020-04-15 21:32 UTC, victoriabernard92 commented
Thanks @maximivanov almost there let me know what you think of my suggestions then I think we can merge

2020-04-15 22:28 UTC, maximivanov commented
Hey @victoriabernard92 thanks for the suggestions, they look great!

Not sure why the build is failing though. It seems like it can't find `./dist/index.js`... does it look in project's root while `dist` folder is in `workers-site/`?

I git-rebased latest changes from the upstream repo's `master` to my branch but it didn't help.

2020-04-16 15:35 UTC, victoriabernard92 commented
@maximivanov Builds are broken because CI isn't running the build step. Not this PR's fault I opened an issue because I've been meaning to fix this:https://github.com/ashleygwilliams/template-registry/issues/23

Sorry for the trouble there.

2020-04-16 15:35 UTC, exvuma approved these changes

2020-04-16 15:36 UTC, merged

2020-05-08 20:44 UTC, maximivanov commented
Hi @victoriabernard92 I just realized this snippet is not appearing on the templates site... not sure whether it's expected or if something is broken.